### PR TITLE
[py-tx] Add copyright header and move newest test file

### PR DESCRIPTION
**Pull request by BarrettOlson**
Summary
---------
Adds copyright header to test added in #368. (Also moves files out to match the test for hashing. I don't feel that strongly about this if @Dcallies prefers where it is now)

Test Plan
---------
```
$ pytest 

platform darwin -- Python 3.8.7, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/barrett/dev/github/ThreatExchange/python-threatexchange
collected 50 items                                                                                                                                                  

tests/test_common.py .                                                                                                                                  [  2%]
tests/cli/cli_smoke_test.py .                                                                                                                           [  4%]
tests/hashing/test_pdq_faiss_matcher.py .......................................                                                          [ 92%]
tests/hashing/test_pdq_utils.py ....                                                                                                               [100%]

====== 50 passed in 0.62s ==============
```

### CODE REVIEW

**Review by schatten — APPROVED** [review]

**Comment by schatten** [comment]
@BarrettOlson I do not see a file move in the diff. Are you sure you checked that in?

**Comment by BarrettOlson** [comment]
> @BarrettOlson I do not see a file move in the diff. Are you sure you checked that in?

yes, see in Files changed: `.../cli/tests/cli_smoke_test.py → .../tests/cli/cli_smoke_test.py`

**Comment by schatten** [comment]
> > @BarrettOlson I do not see a file move in the diff. Are you sure you checked that in?
> 
> yes, see in Files changed: `.../cli/tests/cli_smoke_test.py → .../tests/cli/cli_smoke_test.py`

image

We're good to merge this in now. :)

**Comment by Dcallies** [comment]
I'm not following the reason for the directory change - can you explain that?

To be clear, I'm attempting to follow the following pattern:
To find the test for the file in the directory, look for a test in /tests/ in the same directory

**Comment by BarrettOlson** [comment]
> I'm not following the reason for the directory change - can you explain that?
> 
> To be clear, I'm attempting to follow the following pattern:
> To find the test for the file in the directory, look for a test in /tests/ in the same directory

I don't have a good argument for it besides matching what was done for the hashing lib. So I'll move it back for now.

pytest supports both: https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code
A reason listed in favor of tests outside of the application code:
> Your tests can run against an installed version after executing pip install ..
> Your tests can run against the local copy with an editable install after executing pip install --editable ..
not sure if that outweighs the overhead / the convenience of having test more inline though...

**Pull request merged**
