### PR TITLE
Add review status and share level to search options.

### PR DESCRIPTION
**Pull request by mgoffin**
Adds a 'review_status' and 'share_level' argument to `.objects()` for
limiting search results by those API parameters.

### CODE REVIEW

**Comment by motiwarifacebook** [comment]
I just realized that Malware.objects should also support querying by sample_type as per the docs. This PR lgtm, do you want to merge it now or upload another commit also supporting sample_type queries for Malware.objects?

**Comment by mgoffin** [comment]
Added :)

**Comment by motiwarifacebook** [comment]
You are amazing. Thanks!

**Comment by motiwarifacebook** [comment]
Can you update PyPI when you have a chance?

**Pull request merged**
