### PR TITLE
Have pytx use TLS1.0+ to avoid bad SSL warnings and avoid using bad SSL

### PR DESCRIPTION
**Pull request by ivanlei**
**Let's use TLS!**
This is issue #32

The fix here is real simple. Install the option `secure` requirements for the `requests` package.
See more @ http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

**.gitignore**
Quick update. Add `.DS_Store` which OSX likes to litter the filesystem with.

### CODE REVIEW

**Comment by mgoffin** [comment]
I believe this is for pre-python-2.7.9 users? I wish requests documented that "feature" more as it seems it would be useful for a lot of people.

**Comment by ivanlei** [comment]
Yeah, @mgoffin it's for pre-python-2.7.9 users. I tried to find this documented on http://docs.python-requests.org/en/latest/ or https://pypi.python.org/pypi/requests and I don't think it is. Lemme go fork https://github.com/kennethreitz/requests and document it.

**Comment by mgoffin** [comment]
Is there a situation where requiring `requests[security]` will break for anyone? If not I'm :+1: for this!

**Comment by ivanlei** [comment]
Lemme try to use tox to test that @mgoffin. From https://github.com/kennethreitz/requests/blob/master/setup.py#L65 it seems `requests` is compatible with a wide range of python versions but there's no tests for that.

**Comment by ivanlei** [comment]
Okay. So that last commit adds a `tox.ini` which then installs `pytx` (using both `setup.py` and `requirements.txt`) under:
- py26
- py27
- py33
- py34

As a side benefit, if any further tests are added to `/tests` there's a `tox.ini` ready to run them.

Basically, this verifies there's not a situation where `requests[security]` breaks something.

**Comment by mgoffin** [comment]
Excellent! Looks good :+1:

**Comment by omercnet** [comment]
I concur :) :+1:

**Comment by hammem** [comment]
thanks, @ivanlei !

**Pull request merged**
