### PR TITLE
Moving utility functions to pytx

### PR DESCRIPTION
**Pull request by motiwarifacebook**
@mgoffin what do you think?

### CODE REVIEW

**Comment by mgoffin** [comment]
I think the code looks good.  However, we should probably add a `pytx.utils.rst` into the `docs` directory (copy any one of the ones that's there and there might be one or two changes in the file to make). Also, we might need to add this to `__init__.py` (similar to importing `access_token` in that file) so you can do this:

```python
from pytx.utils import get_time_param
```

If we have that then I think this would be good to commit :)

**Comment by motiwarifacebook** [comment]
@mgoffin  I added your suggested changes and also added the _default_fields we discussed in https://github.com/facebook/ThreatExchange/pull/109

**Comment by hammem** [comment]
@mgoffin / @motiwarifacebook - Let's bump the pytx version number, since we're adding a new dependency.  Unless you want to just wait until #112 gets merged in.

**Comment by mgoffin** [comment]
Yea I think when #112 gets merged we can do a full 0.4.0 release which would include all of this stuff and a few PRs we accepted recently. Just waiting to ensure that #112 is doing things right and there's not any bells/whistles we want to include in it :)

But I think this looks good to go! Thanks @motiwarifacebook!

**Comment by hammem** [comment]
The ayes have it, the motion passes.

**Pull request merged**
