### PR TITLE
Add support for Source URI field on ThreatDescriptor

### PR DESCRIPTION
**Pull request by hammem**
We recently added support for setting/getting a source URI (aka a URL
that points to detailed information about the source or context of the
threat intelligence).  This adds it to pytx.ThreatDescriptor.

### CODE REVIEW

**Comment by mgoffin** [comment]
👍🏻

**Comment by RyPeck** [comment]
@hammem documentation for not out yet or will it be in a future version?

**Comment by hammem** [comment]
@RyPeck , documentation is there now! (Thanks for reminding me)

https://developers.facebook.com/docs/threat-exchange/reference/apis/threat-descriptor/

**Comment by RyPeck** [comment]
@hammem excellent - thanks!

**Pull request merged**
