### PR TITLE
UI: fix positioning on main content

### PR DESCRIPTION
**Pull request by tiegz**
Fixes the sidebar/results list -- the first item in the results list and the sidebar error were being covered up by the navbar.

### CODE REVIEW

**Comment by tiegz** [comment]
done-so!

**Comment by mgoffin** [comment]
Howdy! Just curious what browser you are using for this? With your changes the search bar is now significantly lower than the nav bar which looks weird since the search bar has a different background color. I was not having the issues you were having prior to your changes. This was built using Chrome so it's possible there's a little conflict causing your browser issues though.

**Comment by tiegz** [comment]
@mgoffin I'd tested this on Chrome and Safari, but I think I see the issue now. My browser was open at <1200px wide, which broke the search bar down to the next line. Still worth fixing imo, but I'll try to think of a better approach to fixing this!

**Comment by mgoffin** [comment]
@tiegz Ahh that would do it! Yea I think we'll need a better solution for small window sizes!

**Pull request closed without merging**
