### PR TITLE
Misc design changes to dashboard

### LINKED ISSUE #635: Dashboard Page Design Feedback
*  StatCard should have the following changes made:

    1. The graph should be ‘below’ the header, not above it
    2. Stretch the graph to the full width of the card
    3. Instead of a piece of the legend showing current values on mouse hover, use a tooltip. Uplot has an example. (https://leeoniya.github.io/uPlot/demos/tooltips-closest.html)

* Share an x axis cursor hair across all graphs. uplot example (https://leeoniya.github.io/uPlot/demos/sync-cursor.html)
* Instead of red, use neutral colors. Blue (current accent for HMA), Purple (distinct, yet neutral)

### PR DESCRIPTION
**Pull request by schatten**
Fixes #635 

Summary
---------
* move Graph below header in stat cards
* switch from red to blue for dashboard chart color
* allow graph to expand to fill the space available
* add loading and error state for stat cards

Test Plan
---------
Took screenshots!

### Before
d3jelb9xcmkers cloudfront net_

### After
localhost_3000_

### Failed to load stats
Screen Shot 2021-06-02 at 10 08 42

### Loading gif (manually introduced delays)
hma-dashboard-loading

### CODE REVIEW

**Comment by BarrettOlson** [comment]
Is it worth handling the empty case in this PR?  I'd like to replace the two random spinners we show now (or defaulting true for metrics). Fine punting if not in scope this PR.

**Review by BarrettOlson — APPROVED** [review]
Looks good to me! Accepting to unblock. 

I'm sure this fully closes #635 though
> iii. Instead of a piece of the legend showing current values on mouse hover, use a tooltip. Uplot has an example. (https://leeoniya.github.io/uPlot/demos/tooltips-closest.html)

**Comment by schatten** [comment]
> Looks good to me! Accepting to unblock.
> 
> I'm sure this fully closes #635 though
> 
> > iii. Instead of a piece of the legend showing current values on mouse hover, use a tooltip. Uplot has an example. (https://leeoniya.github.io/uPlot/demos/tooltips-closest.html)

That's correct. I was not able to figure out a super-easy way to do this. Filed https://github.com/facebook/ThreatExchange/projects/2#card-62332134 and moved on instead.

**Review by mengyangwang — APPROVED** [review]
LGTM!

**Pull request merged**
