### PR TITLE
Fixes #1659: Convert image mode I;16 to RGB

### LINKED ISSUE #1659: [pdq] ValueError when computing PDQ hash on some pngs
Getting a rare, sporadic error when computing PDQ hash for certain images

Repro below:
```
$ threatexchange hash photo https://styles.redditmedia.com/t5_6k8ysb/styles/profileIcon_jj0se5l3qgrd1.png
Traceback (most recent call last):
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/bin/threatexchange", line 8, in <module>
    sys.exit(main())
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/lib/python3.8/site-packages/threatexchange/cli/main.py", line 333, in main
    inner_main()
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/lib/python3.8/site-packages/threatexchange/cli/main.py", line 326, in inner_main
    execute_command(settings, namespace)
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/lib/python3.8/site-packages/threatexchange/cli/main.py", line 161, in execute_command
    command.execute(settings)
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/lib/python3.8/site-packages/threatexchange/cli/hash_cmd.py", line 106, in execute
    hash_str = hasher.hash_from_file(file)
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/lib/python3.8/site-packages/threatexchange/signal_type/signal_base.py", line 196, in hash_from_file
    return cls.hash_from_bytes(file.read_bytes())
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/lib/python3.8/site-packages/threatexchange/signal_type/pdq/signal.py", line 79, in hash_from_bytes
    pdq_hash, quality = pdq_from_bytes(bytes_)
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/lib/python3.8/site-packages/threatexchange/signal_type/pdq/pdq_hasher.py", line 32, in pdq_from_bytes
    return _pdq_from_numpy_array(np_array)
  File "/Users/daniel.sun/.pyenv/versions/3.8.12/lib/python3.8/site-packages/threatexchange/signal_type/pdq/pdq_hasher.py", line 36, in _pdq_from_numpy_array
    hash_vector, quality = pdqhash.compute(array)
  File "pdqhash/bindings.pyx", line 66, in pdqhash.bindings.compute
ValueError: Buffer dtype mismatch, expected 'char' but got 'int'
```
Verified this occurs on threatexchange version 1.1.1 (but on python 3.8)

### PR DESCRIPTION
**Pull request by haianhng31**
== Summary ==
* Fixes #1659 
* Convert image mode I;16 to RGB 

== Test Plan ==
* Add test cases for images of mode LA, I;16, RGB

### CODE REVIEW

**Review by Dcallies — CHANGES_REQUESTED** [review]
Thanks a ton for taking this on! I am convinced by your unittests that your PR fixes this issue, but if you can confirm that you can generate a reproduction of the condition with them in your test plan in the summary, I'll be doubly convinced.

A few concerns about the test images, since they appear to be from reddit user data. We don't want to include images we don't have the rights to.

You have a few options for generating test data:
1. Produce the image yourself (essentially donating it the repo)
2. Algorithmically generate the image by generating noise, random data, etc.
3. Mody images in pdq/data/bridge_pics to generate the case, since those were generated by #1 by a previous author.

We cannot do:
1. Images on the internet that we find (even if they are sites purporting to be public domain, because people can re-host images there)
2. Known copyrighted images

Can you try and produce a local reproduction by using the bridge pics? That might be nicest because those hashes have a known value.

**Comment by 16BitNarwhal** [comment]
Hi @Dcallies,
Made some changes and generated test images as follows.
I'm not sure why the quality of the i16 (16-bit grayscale) image is at 36 though
```
from PIL import Image
import numpy as np

width, height = 256, 256

def generate_i16_image():
    noise = np.random.randint(0, 65536, (height, width), dtype=np.uint16)
    image = Image.fromarray(noise, mode='I;16')
    image.save('noise_image_I16.png')

def generate_la_image():
    luminance = np.random.randint(0, 256, (height, width), dtype=np.uint8)
    alpha = np.random.randint(0, 256, (height, width), dtype=np.uint8)
    la_image_data = np.stack((luminance, alpha), axis=-1)
    la_image = Image.fromarray(la_image_data, mode='LA')
    la_image.save('noise_image_LA.png')

def generate_rgb_image():
    red = np.random.randint(0, 256, (height, width), dtype=np.uint8)
    green = np.random.randint(0, 256, (height, width), dtype=np.uint8)
    blue = np.random.randint(0, 256, (height, width), dtype=np.uint8)
    rgb_image_data = np.stack((red, green, blue), axis=-1)
    rgb_image = Image.fromarray(rgb_image_data, mode='RGB')
    rgb_image.save('noise_image_RGB.jpeg', 'JPEG')

generate_i16_image()
generate_la_image()
generate_rgb_image()
```

**Comment by thedanielsun** [comment]
Oh, is this the same issue as what I tried to fix in #1264 ?
I added test data in #1265 idk if that's useful

**Review by Dcallies — APPROVED** [review]
Hmm, I had a reply that seems to have never been submitted -

The reason that your quality is low is that the image quality is low - it's just random noise, and PDQ can detect that and advise against using it for matching!

Instead, we should do as Daniel recommended, which is to use the bridge-mod images, and just convert them. Since this has been sitting for a long time, and there's nothing blocking about this PR, suggest we merge this and iterate if need be.

**Pull request merged**
