### PR TITLE
pytx/scripts/tx.py - A full featured JSON dumper

### PR DESCRIPTION
**Pull request by ivanlei**
This is a simple script for dumping JSON responses from ThreatExchange. It provides a subcommand per API endpoints and dumps simple JSON.

Also, a few very minor comments and docs changes.

### CODE REVIEW

**Comment by ivanlei** [comment]
This failed due to problems with the travis setup which have since been fixed.
Can somebody kick the travis for this again.

**Comment by hammem** [comment]
@ivanlei , I re-ran the Travis build and still get an error:

https://travis-ci.org/facebook/ThreatExchange/builds/66300938

Would you be able to see if there's something that still needs fixing?

**Comment by mgoffin** [comment]
Pretty sure it will continue to fail because the code base at this commit doesn't include the Travis config file (or at least it looks that way from the way Travis ran).

**Comment by hammem** [comment]
Ahh, that was my fear.  If @ivanlei updates the pull request it should fix this, right?

**Comment by jessek** [comment]
@ivanlei Can you please update this pull request or abandon it?

**Comment by Dcallies** [comment]
Closing out due to inactivity.

**Pull request closed without merging**
