### PR TITLE
Add Travis CI Support and link to RTD

### PR DESCRIPTION
**Pull request by mgoffin**
Adds a configuration file for Travis CI (my first time writing one, so be gentle!). Currently it's setup to install dependencies and run tests for pytx only. Theoretically with some hacks it can also support installing dependencies and running tests for the Ruby library if it gets some tests in the future.

This also adds a build badge so once Travis is building we can keep an eye on the status. It also adds a link to readthedocs instead of saying "coming soon".

For Travis CI to work, someone with access to the Facebook ThreatExchange repo needs to go to https://travis-ci.org, then enable builds for this project. Once this is done I believe we can have PyPi doing automated releases of pytx as we tag commits.

### CODE REVIEW

**Comment by hammem** [comment]
Thanks, @mgoffin !  It seems we need admin rights to enable the Travis CI service on the repo.  I should have that sorted soon and we can enable it for cont build.

**Comment by mgoffin** [comment]
@hammem Sounds good! Thank you :)

**Comment by hammem** [comment]
No worries.  I think this will probably work better for us than running a Jenkins instance.  I'm as curious as you to see how it goes.

**Comment by mgoffin** [comment]
Not sure if it's public, but for testing this I used my fork: https://travis-ci.org/mgoffin/ThreatExchange/

**Comment by omercnet** [comment]
great work Mike, looks great!
Sorry I didn't get a change to make some progress on this. Tell me your PyPi user and I'll add you as the package owner, you can then add your info to .travis.yml and have it upload to PyPi when releases are tagged

**Comment by mgoffin** [comment]
@omercnet mgoffin is my pypi user :)

**Comment by omercnet** [comment]
didn't wanna take a chance someone hijacked your user (pytx is getting a lot of traction! :smile:), added you as owner of https://pypi.python.org/pypi/pytx

**Comment by mgoffin** [comment]
Thanks :)

Anything special that I need to do in the .travis.yml outside of "travis setup pypi" to make it deploy properly?

**Comment by omercnet** [comment]
No idea man, I'm also a noob with this :)

**Comment by mgoffin** [comment]
We'll see if that works once everything on both ends are setup :)

**Comment by ivanlei** [comment]
@mgoffin I imitated your {{.travis.yml}} in one of my own projects and it seems to work. I expect this to work. :+1:

**Comment by mgoffin** [comment]
Is there anything else we can do to help move this PR along? All of the other PRs will continue to fail Travis until this PR is accepted (this PR is what will configure Travis to properly build when other PRs are submitted).

**Comment by hammem** [comment]
Thank you, kind sir!

**Pull request merged**
