### PR TITLE
Define 'tx' as additional CLI entry point

### PR DESCRIPTION
**Pull request by dougneal**
Summary
---------

To save those precious keystrokes

Test Plan
---------

`tx -h` - it works

### CODE REVIEW

**Comment by Dcallies** [comment]
Only problem here is that there is another unix tool named `tx`: https://www.unix.com/man-page/linux/1/tx/

Do you have any familiarity with this guy? Should we just stomp it?

**Comment by dougneal** [comment]
> Only problem here is that there is another unix tool named `tx`: https://www.unix.com/man-page/linux/1/tx/
> 
> Do you have any familiarity with this guy? Should we just stomp it?
> 
> We just tell folks to use `alias`

Oh. Well, from reading on what it actually is, the chances of it being installed alongside ThreatExchange are pretty low, I'd say. I don't feel too strongly though. Maybe `thrx` instead of `tx`?

**Comment by BarrettOlson** [comment]
Personally I don't think, `thrx` is worth it. I am fine with leaving it was an alias suggestion but I also agree that the changes for both being installed alongside would be very rare.

**Comment by Dcallies** [comment]
I say let's take `tx`, we can always walk it back to alias later.

**Review by Dcallies — APPROVED** [review]

**Pull request merged**
