### PR TITLE
pytx/docs Add reference to Facebook Docs

### PR DESCRIPTION
**Pull request by RyPeck**
Adding reference to the Facebook Documentation for making multiple
requests and using JSONPath to extract data from those requests.

Took me a bit to find these docs searching - thought a link would be
helpful for anyone else that comes along.

### CODE REVIEW

**Comment by mgoffin** [comment]
:+1:

**Comment by wxsBSD** [comment]
It got a 👍  from @mgoffin? That's always good enough for me! <3

**Comment by RyPeck** [comment]
@mgoffin is updating readthedocs.io a manual step?

**Comment by mgoffin** [comment]
At this time yes. They tried making a github hook to kick off the build but it never worked and I don't think we've looked at it any further. I'll kick one off now.

**Pull request merged**
